= Migration from CUBA

== Update packages

Open the root directory of the front module.

Remove cuba packages:

----
npm uninstall @cuba-platform/react-core @cuba-platform/react-ui @cuba-platform/rest
----

Install Jmix packages:

----
npm install @haulmont/jmix-react-core @haulmont/jmix-react-ui @haulmont/jmix-rest
----

== Change environment

Open `package.json` and add a proxy server to `http://localhost:8080/`:

----
{
  ...
  "proxy": "http://localhost:8080/",
  ...
}
----

Open `src/config.ts` and remove `CUBA_APP_URL` constant and add `JMIX_REST_URL` constant this way:
----
// Before:
export const CUBA_APP_URL = process.env.REACT_APP_CUBA_URL ?? "/app/rest/";

// After:
export const JMIX_REST_URL = process.env.REACT_APP_JMIX_REST_URL ?? "/rest/";
----

Сhange environment variables.

Open `.env.development.local` and `.env.production.local` and rename varaibles in both files this way:

----
PUBLIC_URL=/front/
REACT_APP_JMIX_REST_URL=/rest/
REACT_APP_REST_CLIENT_ID=client
REACT_APP_REST_CLIENT_SECRET=secret
----

== Changes in `src/index.ts`

Add this import for fix mobx https://github.com/mobxjs/mobx-react-lite/#observer-batching-deprecated[Observer batching] warning:

----
After:
import 'mobx-react-lite/batchingForReactDom';
----

Change Jmix REST initialization.

Import `JMIX_REST_URL` constant from `src/config.ts`.
Remove cubaREST initialization. After that add jmixREST initialization this way:

----
// Before:
import { CUBA_APP_URL, REST_CLIENT_ID, REST_CLIENT_SECRET } from "./config";
// After:
import { JMIX_REST_URL, REST_CLIENT_ID, REST_CLIENT_SECRET } from "./config";

// Before:
export const cubaREST = initializeApp({
  name: {project name},
  apiUrl: CUBA_APP_URL,
  restClientId: REST_CLIENT_ID,
  restClientSecret: REST_CLIENT_SECRET,
  storage: window.localStorage,
  defaultLocale: "en"
});

// After:
export const jmixREST = initializeApp({
  name: {project name},
  apiUrl: JMIX_REST_URL,
  restClientId: REST_CLIENT_ID,
  restClientSecret: REST_CLIENT_SECRET,
  storage: window.localStorage,
  defaultLocale: "en"
});
----

Replace `CubaAppProvider` with `JmixAppProvider`.

----
// Before:
ReactDOM.render(
  <CubaAppProvider cubaREST={cubaREST}>
    ...
  </CubaAppProvider>,
  document.getElementById("root") as HTMLElement
);

// After:
ReactDOM.render(
  <JmixAppProvider jmixREST={jmixREST}>
    ...
  </JmixAppProvider>,
  document.getElementById("root") as HTMLElement
);
----

== Rename imports and interfaces

Run application for TypeScript hints.

----
npm run start
----

Replace all imports of cuba packages to the corresponding Jmix packages. Rename the interfaces everywhere in the project.

Imports:

* `@cuba-platform/react-core` -> `@haulmont/jmix-react-core`
* `@cuba-platform/react-ui` -> `@haulmont/jmix-react-ui`
* `@cuba-platform/rest` -> `@haulmont/jmix-rest`

Interfaces:

* `CubaAppProvider` -> `JmixAppProvider`
* `CubaApp` -> `JmixRestConnection`

----
// Before:
import { CubaAppProvider } from "@cuba-platform/react-core";
import { CubaApp } from "@cuba-platform/rest";
import { ... } from "@cuba-platform/react-ui";

// After:
import { JmixAppProvider } from "@haulmont/jmix-react-core";
import { JmixRestConnection } from "@haulmont/jmix-rest";
import { ... } from "@haulmont/jmix-react-ui";
----


== Generate Jmix interfaces

Open the root directory of the front module.

Remove cuba generator package.

----
npm uninstall @cuba-platform/front-generator
----

Install Jmix generator package.

----
npm install @haulmont/jmix-front-generator
----

Open `package.json` and rewrite `update-model` script:

----
// Before:
{
  "scripts": {
    ...
    "update-model": "gen-cuba-front sdk:all --dest src/cuba"
    ...
  }
}

// After:
{
  "scripts": {
    ...
    "update-model": "gen-jmix-front sdk:all --dest src/jmix"
    ...
  }
}
----

Remove `src/cuda/` directory.

Generate new Jmix model classes:

----
npm run update-model
----

Rename imports from `src/cuba/` to `src/jmix/` everywhere in the project.

----
// Before:
import {...} "../cuba/.."

// After:
import {...} "../jmix/.."
----