site:
  title: Jmix Frontend UI Manual
  url: https://docs.jmix.io/
  start_page: jmix-frontend-docs:overview:index.adoc
output:
  dir: docs-build
content:
  sources:
    - url: https://github.com/haulmont/jmix-frontend.git
      branches:
        - master
#        - v[0-9]*
      start_path: docs-src/doc-component-repo
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
asciidoc:
  attributes:
    manual_platform: 'https://docs.jmix.io/jmix/0.x'
    manual_restApi: 'https://docs.jmix.io/jmix/0.x/rest/index.html'
    manual_studio: 'https://docs.jmix.io/jmix/0.x/studio/index.html'
    restApiSwagger: 'http://files.cuba-platform.com/swagger/7.2'
    compositionGuide: 'https://docs.jmix.io/jmix/0.x/data-model/entities.html#references'
    antDesign_base: 'https://ant.design'
    npm_frontendGenerator: 'https://www.npmjs.com/package/@haulmont/jmix-front-generator'
    npm_cubaReactCore: 'https://www.npmjs.com/package/@haulmont/jmix-react-core'
    npm_cubaReactUi: 'https://www.npmjs.com/package/@haulmont/jmix-react-ui'
    npm_cubaRestJs: 'https://www.npmjs.com/package/@haulmont/jmix-rest'
    forum: 'https://www.cuba-platform.com/discuss/c/jmix/40'
    api_rest: 'link:../api-reference/jmix-rest/index.html'
    git_frontendUi: 'https://github.com/Haulmont/jmix-frontend'
