# coverage check config

extends: "@istanbuljs/nyc-config-typescript"
check-coverage: true
skip-full: true

# do not check coverage in this folders
exclude: [
  "src/test/**",
  "src/generators/*/*/template/**",
]

statements: 78
branches: 62
functions: 69
lines: 78
